version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    assignees:
      - "@me"
    reviewers:
      - "@me"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    ignore:
      # Ignore major version updates for stability
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      # Group development dependencies
      dev-dependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier"
          - "vitest"
          - "@vitest/*"
          - "@testing-library/*"
          - "@playwright/*"
          - "husky"
          - "lint-staged"
        update-types:
          - "minor"
          - "patch"
      # Group React ecosystem
      react-ecosystem:
        patterns:
          - "react"
          - "react-*"
          - "@tanstack/*"
        update-types:
          - "minor"
          - "patch"
      # Group UI dependencies
      ui-dependencies:
        patterns:
          - "@radix-ui/*"
          - "lucide-react"
          - "tailwindcss"
          - "@tailwindcss/*"
          - "class-variance-authority"
          - "clsx"
          - "tailwind-merge"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    assignees:
      - "@me"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "ci"
      - "automated"